### ISSUE TITLE
Inconsistent input and output types

### ISSUE THREAD

**Issue by AShiou** [Canner/wren-engine#196]
```
select 123
```
expected type is JDBC INTEGER type, while it is BIGINT type
Since BigQuery only have `int64` type, we should map `int64` to pg BIGINT type

Please check `TestJdbcResultSet` and `TestWireProtocolTypeWithBigQuery`

Some JDBC type need to be corrected
1. TINYINT
2. SMALLINT
3. INTEGER
4. REAL
5. DECIMAL
6. OTHER

**Comment by goldmedal** [comment]
legacy issue.
