### ISSUE TITLE
Refactor type test

### ISSUE THREAD

**Issue by AShiou** [Canner/wren-engine#248]
There are too many types of tests separated into different test classes. We should integrate them together, perhaps allowing them to only change the connecting database.

## Class
- TestWireProtocolType
- TestJdbcResultSet
- TestWireProtocolWithBigquery#testJdbcParamTypes
- TestBigQueryPreAggregation#testType
- TestBigQueryType.java

**Comment by goldmedal** [comment]
legacy issue.
