### ISSUE TITLE
[Following] Duckdb generates decimal fields of a parquet based on int

### ISSUE THREAD

**Issue by liun03** [Canner/wren-engine#306]
Based on concept https://duckdb.org/docs/sql/data_types/numeric.html#fixed-point-decimals:
We sense the decimal type in duckdb is based on int.

BUT, there are some decimal issues with int based values:
https://issues.apache.org/jira/browse/HIVE-21987

We need to follow the issues and hive 4.x fixed the issues.(alpha version)

**Comment by goldmedal** [comment]
legacy issue.
