### ISSUE TITLE
Prepared Statement parameters order may wrong

### ISSUE THREAD

**Issue by AShiou** [Canner/wren-engine#311]
## Description
PostgreSQL support prepared statements with placeholders, like 
```
SELECT $1 as c1, $2 c2
```

Accio would rewrite placeholders to `?` due to use Trino sql base.
```
SELECT ? as c1, ? c2
```

But it may cause some problems if the placeholders in wrong order, like, 
```
SELECT $2 as c1, $1 c2
```

## Possible Solution
Modify sql base to support `$1`, `$2`...

## Related Problem
When query prepared statements, Accio would rewrite PostgreSQL sql to connected database sql, and then add parameters.
If we don't know the parameters order, we can't identify parameter type when rewriting.

For example,  PostgreSQL substring function support `substring(string from int)` and `substring(string from string)`. If we want to rewrite `substring` function to BigQuery function.
```
PostgreSQL substring(string from int) -> BigQuery substring(string, int)
PostgreSQL substring(string from string) -> BigQuery regexp_extract(string, string)
```
But when rewriting, we only know we get parameters but we don't know parameters type, then it's hard to rewrite functions.

**Comment by goldmedal** [comment]
legacy issue.
