### ISSUE TITLE
Fix substring(string from regexp) when the regexp only contains numbers in BigQuery

### ISSUE THREAD

**Issue by AShiou** [Canner/wren-engine#329]
When the dialect is BigQuery, 
```
canner-cml=> select substring('123' from '1');
 substr 
--------
 123
(1 row)
```
When the regex expression is a string only contains numbers, it will be parsed as a number. So `substring('123' from '1')` would get the wrong answer `123`, actual should be `1`.
```
cannerflow-sql-engine=# select substring('123' from '1');
 substring 
-----------
 1
(1 row)
```

**Comment by goldmedal** [comment]
legacy issue.
