### ISSUE TITLE
Use native PostgreSQL result as expected result in AbstractWireProtocolTypeTest

### ISSUE THREAD

**Issue by AShiou** [Canner/wren-engine#363]
In `AbstractWireProtocolTypeTest`, we aim to test that the Wire Protocol type result is the same as the PostgreSQL type result. Therefore, there is no need to manually write the expected result. Instead, we should assert whether the Wire Protocol type result matches the PostgreSQL type result.

### Possible Solution
To achieve this, we can modify the `execute` function in `AbstractWireProtocolTypeTest` to execute the same SQL query separately using PostgreSQL and the Wire Protocol, and then compare the query results.

**Comment by goldmedal** [comment]
legacy issue.
