### ISSUE TITLE
Accio Project Initialization Fails on x86 MacOS Environment

### ISSUE THREAD

**Issue by douenergy** [Canner/wren-engine#371]
I follow the [quick-start page](https://getaccio.ai/docs/get-started/quick-start)
but stuck on `can't find a suitable configuration file in this directory or any parent: not found`

I have successfully run `accio hello` ?

<img width="1042" alt="image" src="https://github.com/Canner/accio/assets/103009868/2b6383f8-c0d7-4bc0-b3bd-4e57b5601ac8">

the following command `accio cli` keep failing. 

```
can't find a suitable configuration file in this directory or any parent: not found

Error  Command failed: docker compose --project-name accio exec engine bash launch-cli.sh
```

BTW i download the binary from [accio.osx.intel.tar.gz](https://github.com/Canner/accio/releases/download/0.1.0/accio.osx.intel.tar.gz)

**Comment by goldmedal** [comment]
Hi @douenergy
After executed `accio hello`, did you find the generated MDL file and json file in your working path?
```
jax@jax-canner:~/workspace/accio-test  $ ls
quick-start.json quick-start.mdl
```

**Comment by douenergy** [comment]
Yeh, Both quick-start.json  and quick-start.mdl are generated.

**Comment by goldmedal** [comment]
It's the full stdout log if you run `accio hello` successfully.
```
jax@jax-canner:~/workspace/accio-binary-test  $ ls    
accio                  accio.osx.intel.tar.gz
jax@jax-canner:~/workspace/accio-binary-test  $ ./accio hello
✔ Initialized Accio
✔ Built quick-start.mdl
⠋ Starting Demo Databaseff5d5895435a3e994a40847d2db8b76d4587976f3e459af0de10f01053b1c099
✔ Started Demo Database
Please set the following configs
config {
  project: "example"
  engine: "postgres"
  schema: "public"
  host: "accio-demo-db"
  username: "accio"
  password: "accio"
}
✔ Environment is ready
✔ Docker network is ready
✔ Serve files are generated
✔ The Accio Path to mount is set
✔ The Config Path to mount is set
✔ The Launch CLI Path to mount is set
[+] Running 4/4o Serve
 ✔ Network accio_default                                                                                                                                      Created                                                                                                                 0.1s 
 ✔ Container accio-admin-ui-1                                                                                                                                 Started                                                                                                                 0.7s 
 ✔ Container accio-engine-1                                                                                                                                   Started                                                                                                                 0.7s 
 ! admin-ui The requested image's platform (linux/arm64/v8) does not match the detected host platform (linux/amd64/v2) and no specific platform was requested                                                                                                                         0.0s 
✔ Accio Serve is started
2023-08-16 03:06:44.193	INFO		CLI	Admin UI is available at http://localhost:3000
```

Could you check if all of steps work fine?
```
✔ Environment is ready
✔ Docker network is ready
✔ Serve files are generated
✔ The Accio Path to mount is set
✔ The Config Path to mount is set
✔ The Launch CLI Path to mount is set
```

The error messages your provided mentions the configuration isn't found. Accio CLI will mount the config path to the accio container. I guess that there're some problems of mounting config path.

<img width="1084" alt="截圖 2023-08-16 上午11 18 12" src="https://github.com/Canner/accio/assets/6974913/7020a4e1-000a-47c5-9098-1dc77bac304c">

**Comment by douenergy** [comment]
Thanks @goldmedal  for the help !
But the `accio cli` is still not working. 

<img width="1152" alt="image" src="https://github.com/Canner/accio/assets/103009868/09adb0aa-3928-46e7-b7b8-489058f488bb">

<img width="1005" alt="image" src="https://github.com/Canner/accio/assets/103009868/0a09d571-e0f9-4640-ad21-e65f6e1d81f9">

**Comment by goldmedal** [comment]
Hi @douenergy 
Could you provide the version of your `docker-compose`? Because `accio cli` executes `docker-compose` implicitly, we found `docker-compose` needs extra yml configuration in some version. I want to reproduce this issue in my laptop.
BTW, the version of `docker-compose` installed in my mac is `v2.19.1`. Maybe you can try this or other version in your laptop. Thanks. :)

**Comment by brandboat** [comment]
Hello, @douenergy, thanks for giving accio a try !
From the error message `can't find a suitable configuration file in this directory or any parent: not found`. Looks like the docker-compose.yml is missing. Is the `docker-compose.yml` exists under the directory in below pictures ? (The pic as belows is a capture of image from your last comment)
![image](https://github.com/Canner/accio/assets/4344302/03c5d3b3-210c-485e-be7e-7b8c8016f963)

**Comment by douenergy** [comment]
When i switch to [orbstack](https://orbstack.dev/ ) , everything works !  (I'll keep my Docker environment as it is now. 🤭)

It is very cool to query TPCH like this 👍

<img width="776" alt="image" src="https://github.com/Canner/accio/assets/103009868/2a56f910-926e-4f44-9c6a-918558fcf8c8">

Thanks @goldmedal
