### ISSUE TITLE
cannot run accio cli

### ISSUE THREAD

**Issue by madman188** [Canner/wren-engine#373]
![image](https://github.com/Canner/accio/assets/144977211/1eea4958-3ce7-4b3d-a78f-8dbcd809dd11)
my ubuntu is Ubuntu 18.04.5 LTS
why?

**Comment by madman188** [comment]
can you suply the source code of accio cli? i guess thart os is diff and make it not work

**Comment by goldmedal** [comment]
> can you suply the source code of accio cli? i guess thart os is diff and make it not work

Hi @madman188, thank you for reporting this issue.
We are currently in the process of reorganizing the source code for accio-cli. It will be released in the next few days.
