### ISSUE TITLE
Fix parameter type of the function in the expression type analyzer for prepare-statement

### ISSUE THREAD

**Issue by grieve54706** [Canner/wren-engine#477]
When we analyze the prepare-statement for the function's return type, we don't have the parameter is what type when it is a `?` at the visitFunctionCall in the ExpressionTypeAnalyzer.
https://github.com/Canner/accio/blob/e94fb56a61216295b57db776cafa6344b579d462/accio-tests/src/test/java/io/accio/testing/bigquery/TestFunctions.java#L109-L115

**Comment by goldmedal** [comment]
legacy issue.
