### ISSUE TITLE
Feature request: add a place to vote for integrations

### ISSUE THREAD

**Issue by qdrddr** [Canner/wren-engine#565]
Would you please consider adding a place where we can vote for the other integrations to help you understand what's most valuable for the users?

I'd like to add the Neo4j Knowledge Graph Database (NoSQL) with the Cypher query language.
Note: Neo4j is capable of also serving as a Vector Database (like Qdrant)

**Comment by wwwy3y3** [comment]
Hi @qdrddr We added a discussion here -> https://github.com/Canner/WrenAI/discussions/327 . Feel free to add a new comment and describe the integration.
