### ISSUE TITLE
WrenAI API endpoint as UserPromptText-to-SQL_Query converter tool

### ISSUE THREAD

**Issue by qdrddr** [Canner/wren-engine#566]
Also does  WrenAI have API endpoint?
I mean can I via API send the text with user prompt and get the converted SQL query from WrenAI?

Basically serving as UserPromptText-to-SQL_Query converter tool.

**Comment by goldmedal** [comment]
> Also does WrenAI have API endpoint? I mean can I via API send the text with user prompt and get the converted SQL query from WrenAI?
> 
> Basically serving as UserPromptText-to-SQL_Query converter tool.

Hi @qdrddr, we have an API you can call directly, but we haven't published our API documentation yet. Someone asked a similar question a few days ago. @wwwy3y3 provided some guides on how to trace the API work in the Discord channel:
https://discord.com/channels/1227143286951514152/1238353430985179208/1240650085474369617

Feel free to check it out and give it a try. I think we may have formal documentation for it soon.

**Comment by qdrddr** [comment]
Is something like websocket supported for this or we currently have to check the endpoint if the task is finished? @goldmedal

**Comment by goldmedal** [comment]
Allow me to pass this question along to @wwwy3y3 and @onlyjackfrost, as they are responsible for API development. They can provide a clearer answer.

**Comment by onlyjackfrost** [comment]
Currently, web socket is not supported, you have to keep pooling to check the status of askingTask.
The result of an askingTask usually consists of an array of elements, each containing a SQL statement. The array typically has a length of 3, but it can be anywhere from 1 to 4.

**Comment by qdrddr** [comment]
Can I add feature request to support sockets? @wwwy3y3 & @onlyjackfrost
Or maybe I just can convert this task into a feature request?

**Comment by wwwy3y3** [comment]
@qdrddr feel free to open another ticket discussing the support of web socket 😁

**Comment by goldmedal** [comment]
Let's move this discussion to WrenAI.
