### ISSUE TITLE
Password with brackets will fail

### ISSUE THREAD

**Issue by grieve54706** [Canner/wren-engine#643]
We make some data sources create ibis connection via connection URL. If the password is with a bracket, ibis will raise the error `ValueError: Invalid IPv6 URL` when `urllib.parse.urlparse(url)`.

Follow https://github.com/ibis-project/ibis/pull/9466.

After the PR merge, we can quote the password before creating the connection.

**Comment by goldmedal** [comment]
https://github.com/ibis-project/ibis/pull/9466 has been merged. We can close this issue after ibis release a new version.
