### ISSUE TITLE
SQL Analysis relation's nodeLocation.line appears wrong number

### ISSUE THREAD

**Issue by andreashimin** [Canner/wren-engine#683]
I found the relation's `nodeLocation.line` mostly appears the wrong line number

### Reference
According to the SQL `string[]` on the left side, the `nodeLocation.line` should be (index + 1) = `6` instead.

![image](https://github.com/user-attachments/assets/3febdefb-e8d9-408c-836d-3778455fda10)

### SQL for Analysis
```sql
SELECT
  "c"."City" AS "_City",
  "o"."OrderId" AS "_OrderId"
FROM
  "customers" AS "c"
  JOIN "orders" AS "o" ON "c"."Id" = "o"."CustomerId"
WHERE
  "o"."Status" = 'completed'
```
JsonString
```json
"SELECT\n  \"c\".\"City\" AS \"_City\",\n  \"o\".\"OrderId\" AS \"_OrderId\"\nFROM\n  \"customers\" AS \"c\"\n  JOIN \"orders\" AS \"o\" ON \"c\".\"Id\" = \"o\".\"CustomerId\"\nWHERE\n  \"o\".\"Status\" = 'completed'"
```

###  Response
[response.json](https://github.com/user-attachments/files/16312046/response.json)

**Comment by andreashimin** [comment]
Hi @goldmedal,

hmm...I see, but since the AI service will return explained snippets from `criteria`,
UI needs to highlight `ON (\"c\".\"Id\" = \"o\".\"CustomerId\")` in this case.

Is it also correct if we get the `nodeLocation` from `exprSources`? 🤔 
Will it have a problem if analysis with complex SQL?

**Comment by goldmedal** [comment]
> hmm...I see, but since the AI service will return explained snippets from `criteria`, UI needs to highlight `ON (\"c\".\"Id\" = \"o\".\"CustomerId\")` in this case.
> 

So, I think what you need is the location of `criteria` and not the location of `INNER_JOIN`, right? 
Maybe we can provide this if you needed. I guess the format could be
```json
{
   "criteria": {
          "expr": "ON (\"c\".\"Id\" = \"o\".\"CustomerId\")",
          "nodeLocation": {
                "line": 6,
                "column": 8
          }
   }
}
```

> Is it also correct if we get the `nodeLocation` from `exprSources`? 🤔 Will it have a problem if analysis with complex SQL?

If you get the locations of `exprSource`s, I believe they will point to expressions like `\"c\".\"Id\"` and `\"o\".\"CustomerId\"`. This should be the general behavior regardless of the complexity of the SQL.

**Comment by andreashimin** [comment]
> So, I think what you need is the location of `criteria` and not the location of `INNER_JOIN`, right? Maybe we can provide this if you needed. I guess the format could be
> 
> ```json
> {
>    "criteria": {
>           "expr": "ON (\"c\".\"Id\" = \"o\".\"CustomerId\")",
>           "nodeLocation": {
>                 "line": 6,
>                 "column": 8
>           }
>    }
> }
> ```
Yeah, that would be appreciated if I could obtain the criteria's `nodeLocation` directly.
