### ISSUE TITLE
Cannot skip checkstyle

### ISSUE THREAD

**Issue by LZZJ** [Canner/wren-engine#772]
Firstly, I git cloned this project. After running the mvn clean package - DskipTests - P exec jar command, the following error occurred.
--------------------------------------------
[ERROR] src\test\java\io\trino\type\TestTypeCalculation.java:[46] (regexp) RegexpMultiline: Line contains carriage return
[ERROR] src\test\java\io\trino\type\TestTypeCalculation.java:[47] (regexp) RegexpMultiline: Line contains carriage return
[ERROR] src\test\java\io\trino\type\TestTypeCalculation.java:[48] (regexp) RegexpMultiline: Line contains carriage return
[ERROR] src\test\java\io\trino\type\TestTypeCalculation.java:[49] (regexp) RegexpMultiline: Line contains carriage return
[ERROR] src\test\java\io\trino\type\TestTypeCalculation.java:[50] (regexp) RegexpMultiline: Line contains carriage return
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for WrenEngine 0.9.2-SNAPSHOT:
[INFO]
[INFO] WrenEngine ......................................... SUCCESS [  4.572 s]
[INFO] trino-parser ....................................... FAILURE [01:04 min]
[INFO] wren-base .......................................... SKIPPED
[INFO] wren-main .......................................... SKIPPED
[INFO] wren-server ........................................ SKIPPED
[INFO] wren-tests ......................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:10 min
[INFO] Finished at: 2024-08-27T18:29:09+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.4.0:check (checkstyle) on project trino-parser: You have 41973 Checkstyle violations. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :trino-parser
--------------------------------------

When I tried using - DCheckstyle. skip=true, I found it didn't work. How should I solve it?
Or do I have any other procedures to follow?

**Comment by goldmedal** [comment]
We use the airlift framework to build this project.
If you want to skip the checkstyle, you can use
```
-Dair.check.skip-extended=true
```

Refer to https://github.com/airlift/airbase/blob/d06221f6d7c7b912d39af4960397aa36936baa9f/airbase/pom.xml#L116

**Comment by LZZJ** [comment]
Thank you. This is of great help to me.

**Comment by goldmedal** [comment]
It seems this issue has been sovled. Let's close it.
