### ISSUE TITLE
Wren core incorrectly convert `ABS(-1)`

### ISSUE THREAD

**Issue by grieve54706** [Canner/wren-engine#873]
**Describe the bug**
Send statement `SELECT ABS(-1)` to wren core will get `SELECT 1 AS "abs(Int64(-1))"`. It's not an executable SQL.

**To Reproduce**
```python
from wren_core import SessionContext

session_context = SessionContext(manifest_str, function_path)
sql = session_context.transform_sql("SELECT ABS(-1)")

# sql = SELECT 1 AS "abs(Int64(-1))"
```

**Wren engine Information**
- Version: 0.11.2

**Comment by goldmedal** [comment]
It's also simplified by `SimplifyExpressionRule`. Fixed by #874
