### ISSUE TITLE
Wren core transform SQL failed `No field named`

### ISSUE THREAD

**Issue by grieve54706** [Canner/wren-engine#923]
```
SELECT array_agg(x) FROM UNNEST([2, 1,-2, 3, -2, 1, 2]) AS x
```
```
Traceback (most recent call last):
  File "wren-engine/ibis-server/app/mdl/rewriter.py", line 88, in rewrite
    return session_context.transform_sql(sql)
Exception: DataFusion error: Schema error: No field named x. Valid fields are x."UNNEST(make_array(Int64(2),Int64(1),Int64(-2),Int64(3),Int64(-2),Int64(1),Int64(2)))".
```

BigQuery ARRAY_AGG function description
https://cloud.google.com/bigquery/docs/reference/standard-sql/aggregate_functions#array_agg

**Comment by goldmedal** [comment]
```
select array_agg(x) FROM UNNEST([2, 1,-2, 3, -2, 1, 2]) as t(x);
```
@grieve54706 You should assign the table alias with the column name. `t(x)`, `t` is the table name and `x` is the column name.

**Comment by grieve54706** [comment]
Hi @goldmedal, thanks for your reply.
I follow your suggestion and it can be passed for wren core.
However, the transformed SQL can not be received for BigQuery.

Source
```sql
SELECT array_agg(x) FROM UNNEST([2, 1,-2, 3, -2, 1, 2]) AS t(x)
```
Planned
```sql
SELECT array_agg(t.x) FROM (SELECT UNNEST([2, 1, -2, 3, -2, 1, 2]) AS "UNNEST(make_array(Int64(2),Int64(1),Int64(-2),Int64(3),Int64(-2),Int64(1),Int64(2)))") AS t (x)
```
Dialect
```sql
SELECT ARRAY_AGG(t.x) FROM (SELECT UNNEST([2, 1, -2, 3, -2, 1, 2]) AS `UNNEST(make_array(Int64(2),Int64(1),Int64(-2),Int64(3),Int64(-2),Int64(1),Int64(2)))`) AS t
```
BigQuery error message
```
google.api_core.exceptions.BadRequest: 400 POST https://bigquery.googleapis.com/bigquery/v2/projects/wrenai/jobs?prettyPrint=false: Syntax error: Unexpected keyword UNNEST at [1:36]
```
Could you help to check it?

**Comment by goldmedal** [comment]
> Planned
> 
> ```sql
> SELECT array_agg(t.x) FROM (SELECT UNNEST([2, 1, -2, 3, -2, 1, 2]) AS "UNNEST(make_array(Int64(2),Int64(1),Int64(-2),Int64(3),Int64(-2),Int64(1),Int64(2)))") AS t (x)
> ```
> 

The planned SQL is a valid SQL for DuckDB and Postgres. I believe it's a SQLglot issue about transpiling the SQL to BigQuery dialect.

**Comment by grieve54706** [comment]
It seems to be another problem. I will create another issue for the Datafusion transforms sql to `SELECT UNNEST` from `SELECT * FROM UNNEST`.
